imports:
  - { resource: "../../Fixture/Resources/config/services.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kommandhub\Foundation\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,EntityHandler/Abstract*,Entity,Migrations,Tests,Kernel.php}'