services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kommandhub\Foundation\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'